//LV-PARAMETER AND LAUNCHPARAMETER
SET SRB_STAGE TO 1.         // SRB STAGES
SET LIFT_STAGE TO 3.      	// LIFTING STAGE
SET PRELAUNCH_STG TO 1.     // PRE LAUNCH STAGE
SET LV_FAIRING TO 1.        // FAIRING EXISTANT
SET LV_ANTENNA TO 1.        // ANTENNA SWITCH
SET LV_ESCAPE TO 0.			    // ESCAPE SYSTEM
SET LV_PCS TO 0.            // PROPELLANT CROSSFEED SYSTEM
SET LV_PCS_STAGE TO 0.      // PROPELLANT CROSSFEED SYSTEM STAGES
