//LV-PARAMETER AND LAUNCHPARAMETER
//VESSEL MAME: EOS 3
SET SRB_STAGE TO 0.         // SRB STAGES
SET LIFT_STAGE TO 2.        // LIFTING STAGE 
SET PRELAUNCH_STG TO 1.     // PRE LAUNCH STAGE
SET LV_FAIRING TO 0.        // FAIRING EXISTANT
SET LV_ANTENNA TO 0.        // ANTENNA SWITCH 
SET LV_ESCAPE TO 1.         // ESCAPE SYSTEM
SET LV_PCS TO 1.            // PROPELLANT CROSSFEED SYSTEM
SET LV_PCS_STAGE TO 1.      // PROPELLANT CROSSFEED SYSTEM STAGES
