//LV-PARAMETER AND LAUNCHPARAMETER
//VESSEL MAME: HERA 1
SET SRB_STAGE TO 0.         // SRB STAGES
SET LIFT_STAGE TO 3.        // LIFTING STAGE
SET PRELAUNCH_STG TO 1.     // PRE LAUNCH STAGE
SET LV_FAIRING TO 0.        // FAIRING EXISTANT
SET LV_ANTENNA TO 1.        // ANTENNA SWITCH
SET LV_ESCAPE TO 1.         // ESCAPE SYSTEM
SET LV_PCS TO 0.            // PROPELLANT CROSSFEED SYSTEM
SET LV_PCS_STAGE TO 0.  	// PROPELLANT CROSSFEED SYSTEM STAGES
