//DIRECTION
SET DIRHDG TO 340.       // DIRECTION OF FLIGHT
SET DIRAP TO 90000.     // TARGET AP

// LV PARAMETERS ARE IN BOOT FILE NOW.
//ADDITIONAL PARAMETER FOR LAUNCH
SET CNTDWN TO 4.        // COUNTDOWN
SET LOG2FILE TO 0.		// LOGGING TO LOGFILE
SET AFTERLTO TO 1.      // DO SOME STUFF AFTER LTO FINISHED.

// ORBIT CONTROL PARAMETERS
SET ORB_RCS TO 0.       // USE RCS IN ORBITAL
